title: Bernhard Haslhofer's Research Profile
email: haslhofer@csh.ac.at
description: "Research Profile of Bernhard Haslhofer; Publications, Projects, Other Stuff."
baseurl: ""
url: "https://bernhardhaslhofer.info"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compact # possible values: nested expanded compact compressed


