# Site settings
title: Bernhard Haslhofer | Research Profile
author: Bernhard Haslhofers
email: bernhard.haslhofer@ait.ac.at
description: "Research Profile of Bernhard Haslhofer; Publications, Projects, Other Stuff."
baseurl: ""
url: "https://bernhardhaslhofer.info"

# Build settings
markdown: kramdown
permalink: pretty
